### ISSUE TITLE
Tiles seem to not be the size 48

### ISSUE THREAD

**Issue by Midas5665** [Davidd0605/CBL--gameDev#11]
A perfect frame with a 16 x 10 tile load has the values width = 780 and height = 520. The math doesn't add up, tileSize being 48. This messes up a lot of formulas that would normally work for calculating the center of the screen

**Comment by Davidd0605** [comment]
Push your changes for allat and ill handle tmrw

**Comment by Midas5665** [comment]
We no longer care about it
